// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: weather/weather.proto

package weather

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	mi := &file_weather_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_weather_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_weather_weather_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinates) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinates) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GetCurrentWeatherRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Location:
	//
	//	*GetCurrentWeatherRequest_City
	//	*GetCurrentWeatherRequest_Coordinates
	Location      isGetCurrentWeatherRequest_Location `protobuf_oneof:"location"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentWeatherRequest) Reset() {
	*x = GetCurrentWeatherRequest{}
	mi := &file_weather_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentWeatherRequest) ProtoMessage() {}

func (x *GetCurrentWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weather_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentWeatherRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentWeatherRequest) Descriptor() ([]byte, []int) {
	return file_weather_weather_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentWeatherRequest) GetLocation() isGetCurrentWeatherRequest_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *GetCurrentWeatherRequest) GetCity() string {
	if x != nil {
		if x, ok := x.Location.(*GetCurrentWeatherRequest_City); ok {
			return x.City
		}
	}
	return ""
}

func (x *GetCurrentWeatherRequest) GetCoordinates() *Coordinates {
	if x != nil {
		if x, ok := x.Location.(*GetCurrentWeatherRequest_Coordinates); ok {
			return x.Coordinates
		}
	}
	return nil
}

type isGetCurrentWeatherRequest_Location interface {
	isGetCurrentWeatherRequest_Location()
}

type GetCurrentWeatherRequest_City struct {
	City string `protobuf:"bytes,1,opt,name=city,proto3,oneof"`
}

type GetCurrentWeatherRequest_Coordinates struct {
	Coordinates *Coordinates `protobuf:"bytes,2,opt,name=coordinates,proto3,oneof"`
}

func (*GetCurrentWeatherRequest_City) isGetCurrentWeatherRequest_Location() {}

func (*GetCurrentWeatherRequest_Coordinates) isGetCurrentWeatherRequest_Location() {}

type GetCurrentWeatherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Elevation     float64                `protobuf:"fixed64,4,opt,name=elevation,proto3" json:"elevation,omitempty"`
	Temperature   float64                `protobuf:"fixed64,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	FeelsLike     float64                `protobuf:"fixed64,6,opt,name=feels_like,json=feelsLike,proto3" json:"feels_like,omitempty"`
	Humidity      int32                  `protobuf:"varint,7,opt,name=humidity,proto3" json:"humidity,omitempty"`
	WindSpeed     float64                `protobuf:"fixed64,8,opt,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"`
	Condition     string                 `protobuf:"bytes,9,opt,name=condition,proto3" json:"condition,omitempty"`
	Time          string                 `protobuf:"bytes,10,opt,name=time,proto3" json:"time,omitempty"`
	Timezone      string                 `protobuf:"bytes,11,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentWeatherResponse) Reset() {
	*x = GetCurrentWeatherResponse{}
	mi := &file_weather_weather_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentWeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentWeatherResponse) ProtoMessage() {}

func (x *GetCurrentWeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weather_weather_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentWeatherResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentWeatherResponse) Descriptor() ([]byte, []int) {
	return file_weather_weather_proto_rawDescGZIP(), []int{2}
}

func (x *GetCurrentWeatherResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetCurrentWeatherResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetCurrentWeatherResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetCurrentWeatherResponse) GetElevation() float64 {
	if x != nil {
		return x.Elevation
	}
	return 0
}

func (x *GetCurrentWeatherResponse) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GetCurrentWeatherResponse) GetFeelsLike() float64 {
	if x != nil {
		return x.FeelsLike
	}
	return 0
}

func (x *GetCurrentWeatherResponse) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *GetCurrentWeatherResponse) GetWindSpeed() float64 {
	if x != nil {
		return x.WindSpeed
	}
	return 0
}

func (x *GetCurrentWeatherResponse) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *GetCurrentWeatherResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *GetCurrentWeatherResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type GetForecastRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Location:
	//
	//	*GetForecastRequest_City
	//	*GetForecastRequest_Coordinates
	Location      isGetForecastRequest_Location `protobuf_oneof:"location"`
	Days          int32                         `protobuf:"varint,3,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastRequest) Reset() {
	*x = GetForecastRequest{}
	mi := &file_weather_weather_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastRequest) ProtoMessage() {}

func (x *GetForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weather_weather_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastRequest.ProtoReflect.Descriptor instead.
func (*GetForecastRequest) Descriptor() ([]byte, []int) {
	return file_weather_weather_proto_rawDescGZIP(), []int{3}
}

func (x *GetForecastRequest) GetLocation() isGetForecastRequest_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *GetForecastRequest) GetCity() string {
	if x != nil {
		if x, ok := x.Location.(*GetForecastRequest_City); ok {
			return x.City
		}
	}
	return ""
}

func (x *GetForecastRequest) GetCoordinates() *Coordinates {
	if x != nil {
		if x, ok := x.Location.(*GetForecastRequest_Coordinates); ok {
			return x.Coordinates
		}
	}
	return nil
}

func (x *GetForecastRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type isGetForecastRequest_Location interface {
	isGetForecastRequest_Location()
}

type GetForecastRequest_City struct {
	City string `protobuf:"bytes,1,opt,name=city,proto3,oneof"`
}

type GetForecastRequest_Coordinates struct {
	Coordinates *Coordinates `protobuf:"bytes,2,opt,name=coordinates,proto3,oneof"`
}

func (*GetForecastRequest_City) isGetForecastRequest_Location() {}

func (*GetForecastRequest_Coordinates) isGetForecastRequest_Location() {}

type ForecastDay struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Date                     string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	TempMin                  float64                `protobuf:"fixed64,2,opt,name=temp_min,json=tempMin,proto3" json:"temp_min,omitempty"`
	TempMax                  float64                `protobuf:"fixed64,3,opt,name=temp_max,json=tempMax,proto3" json:"temp_max,omitempty"`
	PrecipitationProbability int32                  `protobuf:"varint,4,opt,name=precipitation_probability,json=precipitationProbability,proto3" json:"precipitation_probability,omitempty"`
	Condition                string                 `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ForecastDay) Reset() {
	*x = ForecastDay{}
	mi := &file_weather_weather_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastDay) ProtoMessage() {}

func (x *ForecastDay) ProtoReflect() protoreflect.Message {
	mi := &file_weather_weather_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastDay.ProtoReflect.Descriptor instead.
func (*ForecastDay) Descriptor() ([]byte, []int) {
	return file_weather_weather_proto_rawDescGZIP(), []int{4}
}

func (x *ForecastDay) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ForecastDay) GetTempMin() float64 {
	if x != nil {
		return x.TempMin
	}
	return 0
}

func (x *ForecastDay) GetTempMax() float64 {
	if x != nil {
		return x.TempMax
	}
	return 0
}

func (x *ForecastDay) GetPrecipitationProbability() int32 {
	if x != nil {
		return x.PrecipitationProbability
	}
	return 0
}

func (x *ForecastDay) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type GetForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Elevation     float64                `protobuf:"fixed64,4,opt,name=elevation,proto3" json:"elevation,omitempty"`
	Days          []*ForecastDay         `protobuf:"bytes,5,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastResponse) Reset() {
	*x = GetForecastResponse{}
	mi := &file_weather_weather_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastResponse) ProtoMessage() {}

func (x *GetForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weather_weather_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastResponse.ProtoReflect.Descriptor instead.
func (*GetForecastResponse) Descriptor() ([]byte, []int) {
	return file_weather_weather_proto_rawDescGZIP(), []int{5}
}

func (x *GetForecastResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetForecastResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetForecastResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetForecastResponse) GetElevation() float64 {
	if x != nil {
		return x.Elevation
	}
	return 0
}

func (x *GetForecastResponse) GetDays() []*ForecastDay {
	if x != nil {
		return x.Days
	}
	return nil
}

var File_weather_weather_proto protoreflect.FileDescriptor

const file_weather_weather_proto_rawDesc = "" +
	"\n" +
	"\x15weather/weather.proto\x12\aweather\"G\n" +
	"\vCoordinates\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"v\n" +
	"\x18GetCurrentWeatherRequest\x12\x14\n" +
	"\x04city\x18\x01 \x01(\tH\x00R\x04city\x128\n" +
	"\vcoordinates\x18\x02 \x01(\v2\x14.weather.CoordinatesH\x00R\vcoordinatesB\n" +
	"\n" +
	"\blocation\"\xd1\x02\n" +
	"\x19GetCurrentWeatherResponse\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\televation\x18\x04 \x01(\x01R\televation\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"feels_like\x18\x06 \x01(\x01R\tfeelsLike\x12\x1a\n" +
	"\bhumidity\x18\a \x01(\x05R\bhumidity\x12\x1d\n" +
	"\n" +
	"wind_speed\x18\b \x01(\x01R\twindSpeed\x12\x1c\n" +
	"\tcondition\x18\t \x01(\tR\tcondition\x12\x12\n" +
	"\x04time\x18\n" +
	" \x01(\tR\x04time\x12\x1a\n" +
	"\btimezone\x18\v \x01(\tR\btimezone\"\x84\x01\n" +
	"\x12GetForecastRequest\x12\x14\n" +
	"\x04city\x18\x01 \x01(\tH\x00R\x04city\x128\n" +
	"\vcoordinates\x18\x02 \x01(\v2\x14.weather.CoordinatesH\x00R\vcoordinates\x12\x12\n" +
	"\x04days\x18\x03 \x01(\x05R\x04daysB\n" +
	"\n" +
	"\blocation\"\xb2\x01\n" +
	"\vForecastDay\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x19\n" +
	"\btemp_min\x18\x02 \x01(\x01R\atempMin\x12\x19\n" +
	"\btemp_max\x18\x03 \x01(\x01R\atempMax\x12;\n" +
	"\x19precipitation_probability\x18\x04 \x01(\x05R\x18precipitationProbability\x12\x1c\n" +
	"\tcondition\x18\x05 \x01(\tR\tcondition\"\xab\x01\n" +
	"\x13GetForecastResponse\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\televation\x18\x04 \x01(\x01R\televation\x12(\n" +
	"\x04days\x18\x05 \x03(\v2\x14.weather.ForecastDayR\x04days2\xb6\x01\n" +
	"\x0eWeatherService\x12Z\n" +
	"\x11GetCurrentWeather\x12!.weather.GetCurrentWeatherRequest\x1a\".weather.GetCurrentWeatherResponse\x12H\n" +
	"\vGetForecast\x12\x1b.weather.GetForecastRequest\x1a\x1c.weather.GetForecastResponseB1Z/github.com/wxvn/grpc-mesh/proto/weather;weatherb\x06proto3"

var (
	file_weather_weather_proto_rawDescOnce sync.Once
	file_weather_weather_proto_rawDescData []byte
)

func file_weather_weather_proto_rawDescGZIP() []byte {
	file_weather_weather_proto_rawDescOnce.Do(func() {
		file_weather_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weather_weather_proto_rawDesc), len(file_weather_weather_proto_rawDesc)))
	})
	return file_weather_weather_proto_rawDescData
}

var file_weather_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_weather_weather_proto_goTypes = []any{
	(*Coordinates)(nil),               // 0: weather.Coordinates
	(*GetCurrentWeatherRequest)(nil),  // 1: weather.GetCurrentWeatherRequest
	(*GetCurrentWeatherResponse)(nil), // 2: weather.GetCurrentWeatherResponse
	(*GetForecastRequest)(nil),        // 3: weather.GetForecastRequest
	(*ForecastDay)(nil),               // 4: weather.ForecastDay
	(*GetForecastResponse)(nil),       // 5: weather.GetForecastResponse
}
var file_weather_weather_proto_depIdxs = []int32{
	0, // 0: weather.GetCurrentWeatherRequest.coordinates:type_name -> weather.Coordinates
	0, // 1: weather.GetForecastRequest.coordinates:type_name -> weather.Coordinates
	4, // 2: weather.GetForecastResponse.days:type_name -> weather.ForecastDay
	1, // 3: weather.WeatherService.GetCurrentWeather:input_type -> weather.GetCurrentWeatherRequest
	3, // 4: weather.WeatherService.GetForecast:input_type -> weather.GetForecastRequest
	2, // 5: weather.WeatherService.GetCurrentWeather:output_type -> weather.GetCurrentWeatherResponse
	5, // 6: weather.WeatherService.GetForecast:output_type -> weather.GetForecastResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_weather_weather_proto_init() }
func file_weather_weather_proto_init() {
	if File_weather_weather_proto != nil {
		return
	}
	file_weather_weather_proto_msgTypes[1].OneofWrappers = []any{
		(*GetCurrentWeatherRequest_City)(nil),
		(*GetCurrentWeatherRequest_Coordinates)(nil),
	}
	file_weather_weather_proto_msgTypes[3].OneofWrappers = []any{
		(*GetForecastRequest_City)(nil),
		(*GetForecastRequest_Coordinates)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weather_weather_proto_rawDesc), len(file_weather_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_weather_weather_proto_goTypes,
		DependencyIndexes: file_weather_weather_proto_depIdxs,
		MessageInfos:      file_weather_weather_proto_msgTypes,
	}.Build()
	File_weather_weather_proto = out.File
	file_weather_weather_proto_goTypes = nil
	file_weather_weather_proto_depIdxs = nil
}
