// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: url/url.proto

package urlshortener

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLRequest) Reset() {
	*x = CreateShortURLRequest{}
	mi := &file_url_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLRequest) ProtoMessage() {}

func (x *CreateShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLRequest.ProtoReflect.Descriptor instead.
func (*CreateShortURLRequest) Descriptor() ([]byte, []int) {
	return file_url_url_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortCode     string                 `protobuf:"bytes,2,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,4,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	Clicks        int64                  `protobuf:"varint,5,opt,name=clicks,proto3" json:"clicks,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLResponse) Reset() {
	*x = CreateShortURLResponse{}
	mi := &file_url_url_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLResponse) ProtoMessage() {}

func (x *CreateShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_url_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLResponse.ProtoReflect.Descriptor instead.
func (*CreateShortURLResponse) Descriptor() ([]byte, []int) {
	return file_url_url_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortURLResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateShortURLResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *CreateShortURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *CreateShortURLResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *CreateShortURLResponse) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *CreateShortURLResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetMyURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyURLsRequest) Reset() {
	*x = GetMyURLsRequest{}
	mi := &file_url_url_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyURLsRequest) ProtoMessage() {}

func (x *GetMyURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_url_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyURLsRequest.ProtoReflect.Descriptor instead.
func (*GetMyURLsRequest) Descriptor() ([]byte, []int) {
	return file_url_url_proto_rawDescGZIP(), []int{2}
}

func (x *GetMyURLsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMyURLsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetMyURLsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Urls          []*CreateShortURLResponse `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyURLsResponse) Reset() {
	*x = GetMyURLsResponse{}
	mi := &file_url_url_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyURLsResponse) ProtoMessage() {}

func (x *GetMyURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_url_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyURLsResponse.ProtoReflect.Descriptor instead.
func (*GetMyURLsResponse) Descriptor() ([]byte, []int) {
	return file_url_url_proto_rawDescGZIP(), []int{3}
}

func (x *GetMyURLsResponse) GetUrls() []*CreateShortURLResponse {
	if x != nil {
		return x.Urls
	}
	return nil
}

type GetURLStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLStatsRequest) Reset() {
	*x = GetURLStatsRequest{}
	mi := &file_url_url_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLStatsRequest) ProtoMessage() {}

func (x *GetURLStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_url_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLStatsRequest.ProtoReflect.Descriptor instead.
func (*GetURLStatsRequest) Descriptor() ([]byte, []int) {
	return file_url_url_proto_rawDescGZIP(), []int{4}
}

func (x *GetURLStatsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetURLStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortCode     string                 `protobuf:"bytes,2,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,4,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	Clicks        int64                  `protobuf:"varint,5,opt,name=clicks,proto3" json:"clicks,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLStatsResponse) Reset() {
	*x = GetURLStatsResponse{}
	mi := &file_url_url_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLStatsResponse) ProtoMessage() {}

func (x *GetURLStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_url_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLStatsResponse.ProtoReflect.Descriptor instead.
func (*GetURLStatsResponse) Descriptor() ([]byte, []int) {
	return file_url_url_proto_rawDescGZIP(), []int{5}
}

func (x *GetURLStatsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetURLStatsResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *GetURLStatsResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *GetURLStatsResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *GetURLStatsResponse) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *GetURLStatsResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DeleteURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteURLRequest) Reset() {
	*x = DeleteURLRequest{}
	mi := &file_url_url_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLRequest) ProtoMessage() {}

func (x *DeleteURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_url_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLRequest.ProtoReflect.Descriptor instead.
func (*DeleteURLRequest) Descriptor() ([]byte, []int) {
	return file_url_url_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteURLRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteURLResponse) Reset() {
	*x = DeleteURLResponse{}
	mi := &file_url_url_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLResponse) ProtoMessage() {}

func (x *DeleteURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_url_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLResponse.ProtoReflect.Descriptor instead.
func (*DeleteURLResponse) Descriptor() ([]byte, []int) {
	return file_url_url_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteURLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_url_url_proto protoreflect.FileDescriptor

const file_url_url_proto_rawDesc = "" +
	"\n" +
	"\rurl/url.proto\x12\furlshortener\")\n" +
	"\x15CreateShortURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xbe\x01\n" +
	"\x16CreateShortURLResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"short_code\x18\x02 \x01(\tR\tshortCode\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x04 \x01(\tR\voriginalUrl\x12\x16\n" +
	"\x06clicks\x18\x05 \x01(\x03R\x06clicks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"@\n" +
	"\x10GetMyURLsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"M\n" +
	"\x11GetMyURLsResponse\x128\n" +
	"\x04urls\x18\x01 \x03(\v2$.urlshortener.CreateShortURLResponseR\x04urls\"$\n" +
	"\x12GetURLStatsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xbb\x01\n" +
	"\x13GetURLStatsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"short_code\x18\x02 \x01(\tR\tshortCode\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x04 \x01(\tR\voriginalUrl\x12\x16\n" +
	"\x06clicks\x18\x05 \x01(\x03R\x06clicks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\"\n" +
	"\x10DeleteURLRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x11DeleteURLResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe2\x02\n" +
	"\x13URLShortenerService\x12[\n" +
	"\x0eCreateShortURL\x12#.urlshortener.CreateShortURLRequest\x1a$.urlshortener.CreateShortURLResponse\x12L\n" +
	"\tGetMyURLs\x12\x1e.urlshortener.GetMyURLsRequest\x1a\x1f.urlshortener.GetMyURLsResponse\x12R\n" +
	"\vGetURLStats\x12 .urlshortener.GetURLStatsRequest\x1a!.urlshortener.GetURLStatsResponse\x12L\n" +
	"\tDeleteURL\x12\x1e.urlshortener.DeleteURLRequest\x1a\x1f.urlshortener.DeleteURLResponseB;Z9github.com/wxvn/grpc-mesh/proto/urlshortener;urlshortenerb\x06proto3"

var (
	file_url_url_proto_rawDescOnce sync.Once
	file_url_url_proto_rawDescData []byte
)

func file_url_url_proto_rawDescGZIP() []byte {
	file_url_url_proto_rawDescOnce.Do(func() {
		file_url_url_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_url_proto_rawDesc), len(file_url_url_proto_rawDesc)))
	})
	return file_url_url_proto_rawDescData
}

var file_url_url_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_url_url_proto_goTypes = []any{
	(*CreateShortURLRequest)(nil),  // 0: urlshortener.CreateShortURLRequest
	(*CreateShortURLResponse)(nil), // 1: urlshortener.CreateShortURLResponse
	(*GetMyURLsRequest)(nil),       // 2: urlshortener.GetMyURLsRequest
	(*GetMyURLsResponse)(nil),      // 3: urlshortener.GetMyURLsResponse
	(*GetURLStatsRequest)(nil),     // 4: urlshortener.GetURLStatsRequest
	(*GetURLStatsResponse)(nil),    // 5: urlshortener.GetURLStatsResponse
	(*DeleteURLRequest)(nil),       // 6: urlshortener.DeleteURLRequest
	(*DeleteURLResponse)(nil),      // 7: urlshortener.DeleteURLResponse
}
var file_url_url_proto_depIdxs = []int32{
	1, // 0: urlshortener.GetMyURLsResponse.urls:type_name -> urlshortener.CreateShortURLResponse
	0, // 1: urlshortener.URLShortenerService.CreateShortURL:input_type -> urlshortener.CreateShortURLRequest
	2, // 2: urlshortener.URLShortenerService.GetMyURLs:input_type -> urlshortener.GetMyURLsRequest
	4, // 3: urlshortener.URLShortenerService.GetURLStats:input_type -> urlshortener.GetURLStatsRequest
	6, // 4: urlshortener.URLShortenerService.DeleteURL:input_type -> urlshortener.DeleteURLRequest
	1, // 5: urlshortener.URLShortenerService.CreateShortURL:output_type -> urlshortener.CreateShortURLResponse
	3, // 6: urlshortener.URLShortenerService.GetMyURLs:output_type -> urlshortener.GetMyURLsResponse
	5, // 7: urlshortener.URLShortenerService.GetURLStats:output_type -> urlshortener.GetURLStatsResponse
	7, // 8: urlshortener.URLShortenerService.DeleteURL:output_type -> urlshortener.DeleteURLResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_url_url_proto_init() }
func file_url_url_proto_init() {
	if File_url_url_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_url_proto_rawDesc), len(file_url_url_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_url_proto_goTypes,
		DependencyIndexes: file_url_url_proto_depIdxs,
		MessageInfos:      file_url_url_proto_msgTypes,
	}.Build()
	File_url_url_proto = out.File
	file_url_url_proto_goTypes = nil
	file_url_url_proto_depIdxs = nil
}
